package(default_visibility = ["//visibility:public"])
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library")

scala_library(
        name = "idslpayload",
        srcs = glob(
            ["src/main/scala/**/*.scala"],
        ),
        resources = glob(
            ["src/main/resources/**/*"],
        ),
        #deps = [
            #"@io_bazel_rules_scala_scala_compiler//:io_bazel_rules_scala_scala_compiler",
            #"@io_bazel_rules_scala_scala_library//:io_bazel_rules_scala_scala_library",
        #],
)

